from abc import ABC

from app.services.spelling.modules.base_module import COMPOSITION_CHARS, AccentAugmenter


class MissingDialectHandler(AccentAugmenter, ABC):
    def __init__(self, name='MissingDialectAugmenter', min_char=2, aug_char_p=0.3,
                 aug_word_min=1, aug_word_max=100, aug_word_p=0.3, tokenizer=None, reverse_tokenizer=None,
                 stopwords=None, verbose=0, stopwords_regex=None):
        super().__init__(
            name=name, min_char=min_char, aug_char_p=aug_char_p, aug_word_min=aug_word_min,
            aug_word_max=aug_word_max, aug_word_p=aug_word_p, tokenizer=tokenizer,
            reverse_tokenizer=reverse_tokenizer, stopwords=stopwords,
            verbose=verbose, stopwords_regex=stopwords_regex)

        self.model = {
            "á": ["a"], "à": ["a"],
            "ạ": ["a"], "ả": ["a"],
            "ã": ["a"], "â": ["a"],
            "ấ": ["a", "â", "á"], "ầ": ["a", "â", "à"],
            "ậ": ["a", "â", "ạ"], "ẩ": ["a", "â", "ả"],
            "ẫ": ["a", "â", "ẫ"], "ă": ["a"],
            "ắ": ["a", "ă", "á"], "ằ": ["a", "ă", "à"],
            "ặ": ["a", "ă", "ạ"], "ẳ": ["a", "ă", "ạ"],
            "ẵ": ["a", "ă", "ã"], "í": ["i"],
            "ì": ["i"], "ỉ": ["i"],
            "ĩ": ["i"], "ị": ["i"],
            "ú": ["u"], "ù": ["u"],
            "ủ": ["u"], "ũ": ["u"],
            "ụ": ["u"], "ư": ["u"],
            "ứ": ["u", "ư", "ú"], "ừ": ["u", "ư", "ù"],
            "ử": ["u", "ư", "ủ"], "ữ": ["u", "ư", "ũ"],
            "ự": ["u", "ư", "ụ"], "é": ["e"],
            "è": ["e"], "ẻ": ["e"],
            "ẽ": ["e"], "ẹ": ["e"],
            "ê": ["e"], "ế": ["e", "ê", "é"],
            "ề": ["e", "ê", "è"], "ể": ["e", "ê", "ẻ"],
            "ễ": ["e", "ê", "ẽ"], "ệ": ["e", "ê", "ẹ"],
            "ó": ["o"], "ò": ["o"],
            "ỏ": ["o"], "õ": ["o"],
            "ọ": ["o"], "ô": ["o"],
            "ố": ["o", "ô", "ó"], "ồ": ["o", "ô", "ò"],
            "ổ": ["o", "ô", "ỏ"], "ỗ": ["o", "ô", "õ"],
            "ộ": ["o", "ô", "ọ"], "ơ": ["o"],
            "ớ": ["o", "ơ", "ó"], "ờ": ["o", "ơ", "ò"],
            "ở": ["o", "ơ", "ỏ"], "ỡ": ["o", "ơ", "õ"],
            "ợ": ["o", "ơ", "ọ"], 'đ': ['d'],
            "ý": ["y"], "ỳ": ["y"],
            "ỷ": ["y"], "ỹ": ["y"],
            "ỵ": ["y"]
        }
        self.eligibleCharacters = COMPOSITION_CHARS


class NoDialectHandler(AccentAugmenter, ABC):
    def __init__(self, name='NoDialectAugmenter', min_char=2, aug_char_p=0.3,
                 aug_word_min=1, aug_word_max=100, aug_word_p=0.3, tokenizer=None, reverse_tokenizer=None,
                 stopwords=None, verbose=0, stopwords_regex=None):
        super().__init__(
            name=name, min_char=min_char, aug_char_p=aug_char_p, aug_word_min=aug_word_min,
            aug_word_max=aug_word_max, aug_word_p=aug_word_p, tokenizer=tokenizer,
            reverse_tokenizer=reverse_tokenizer, stopwords=stopwords,
            verbose=verbose, stopwords_regex=stopwords_regex)

        self.model = {
            "á": ["a"], "à": ["a"],
            "ạ": ["a"], "ả": ["a"],
            "ã": ["a"], "â": ["a"],
            "ấ": ["a"], "ầ": ["a"],
            "ậ": ["a"], "ẩ": ["a"],
            "ẫ": ["a"], "ă": ["a"],
            "ắ": ["a"], "ằ": ["a"],
            "ặ": ["a"], "ẳ": ["a"],
            "ẵ": ["a"], "í": ["i"],
            "ì": ["i"], "ỉ": ["i"],
            "ĩ": ["i"], "ị": ["i"],
            "ú": ["u"], "ù": ["u"],
            "ủ": ["u"], "ũ": ["u"],
            "ụ": ["u"], "ư": ["u"],
            "ứ": ["u"], "ừ": ["u"],
            "ử": ["u"], "ữ": ["u"],
            "ự": ["u"], "é": ["e"],
            "è": ["e"], "ẻ": ["e"],
            "ẽ": ["e"], "ẹ": ["e"],
            "ê": ["e"], "ế": ["e"],
            "ề": ["e"], "ể": ["e"],
            "ễ": ["e"], "ệ": ["e"],
            "ó": ["o"], "ò": ["o"],
            "ỏ": ["o"], "õ": ["o"],
            "ọ": ["o"], "ô": ["o"],
            "ố": ["o"], "ồ": ["o"],
            "ổ": ["o"], "ỗ": ["o"],
            "ộ": ["o"], "ơ": ["o"],
            "ớ": ["o"], "ờ": ["o"],
            "ở": ["o"], "ỡ": ["o"],
            "ợ": ["o"], 'đ': ['d'],
            "ý": ["y"], "ỳ": ["y"],
            "ỷ": ["y"], "ỹ": ["y"],
            "ỵ": ["y"]
        }
        self.eligibleCharacters = COMPOSITION_CHARS


class WrongDialectHandler(AccentAugmenter, ABC):
    def __init__(self, name='WrongDialectAugmenter', min_char=2, aug_char_p=0.3,
                 aug_word_min=1, aug_word_max=100, aug_word_p=0.3, tokenizer=None, reverse_tokenizer=None,
                 stopwords=None, verbose=0, stopwords_regex=None):
        super().__init__(
            name=name, min_char=min_char, aug_char_p=aug_char_p, aug_word_min=aug_word_min,
            aug_word_max=aug_word_max, aug_word_p=aug_word_p, tokenizer=tokenizer,
            reverse_tokenizer=reverse_tokenizer, stopwords=stopwords,
            verbose=verbose, stopwords_regex=stopwords_regex)
        self.model = {
            'a': ['á', 'à', 'ạ', 'ả', 'ã'],
            'e': ['é', 'è', 'ẻ', 'ẽ', 'ẹ'],
            'i': ['í', 'ì', 'ỉ', 'ĩ', 'ị'],
            'o': ['ó', 'ò', 'ỏ', 'õ', 'ọ'],
            'u': ['ú', 'ù', 'ủ', 'ũ', 'ụ'],
            'y': ['ý', 'ỳ', 'ỷ', 'ỹ', 'ỵ'],
            'à': ['a', 'á', 'ạ', 'ả', 'ã'],
            'á': ['a', 'à', 'ạ', 'ả', 'ã'],
            'â': ['ấ', 'ầ', 'ậ', 'ẩ', 'ẫ'],
            'ã': ['a', 'á', 'à', 'ạ', 'ả'],
            'è': ['e', 'é', 'ẻ', 'ẽ', 'ẹ'],
            'é': ['e', 'è', 'ẻ', 'ẽ', 'ẹ'],
            'ê': ['ế', 'ề', 'ể', 'ễ', 'ệ'],
            'ì': ['i', 'í', 'ỉ', 'ĩ', 'ị'],
            'í': ['i', 'ì', 'ỉ', 'ĩ', 'ị'],
            'ò': ['o', 'ó', 'ỏ', 'õ', 'ọ'],
            'ó': ['o', 'ò', 'ỏ', 'õ', 'ọ'],
            'ô': ['ố', 'ồ', 'ổ', 'ỗ', 'ộ'],
            'õ': ['o', 'ó', 'ò', 'ỏ', 'ọ'],
            'ù': ['u', 'ú', 'ủ', 'ũ', 'ụ'],
            'ú': ['u', 'ù', 'ủ', 'ũ', 'ụ'],
            'ý': ['y', 'ỳ', 'ỷ', 'ỹ', 'ỵ'],
            'ă': ['ắ', 'ằ', 'ặ', 'ẳ', 'ẵ'],
            'ĩ': ['i', 'í', 'ì', 'ỉ', 'ị'],
            'ũ': ['u', 'ú', 'ù', 'ủ', 'ụ'],
            'ơ': ['ớ', 'ờ', 'ở', 'ỡ', 'ợ'],
            'ư': ['ứ', 'ừ', 'ử', 'ữ', 'ự'],
            'ạ': ['a', 'á', 'à', 'ả', 'ã'],
            'ả': ['a', 'á', 'à', 'ạ', 'ã'],
            'ấ': ['â', 'ầ', 'ậ', 'ẩ', 'ẫ'],
            'ầ': ['â', 'ấ', 'ậ', 'ẩ', 'ẫ'],
            'ẩ': ['â', 'ấ', 'ầ', 'ậ', 'ẫ'],
            'ẫ': ['â', 'ấ', 'ầ', 'ậ', 'ẩ'],
            'ậ': ['â', 'ấ', 'ầ', 'ẩ', 'ẫ'],
            'ắ': ['ă', 'ằ', 'ặ', 'ẳ', 'ẵ'],
            'ằ': ['ă', 'ắ', 'ặ', 'ẳ', 'ẵ'],
            'ẳ': ['ă', 'ắ', 'ằ', 'ặ', 'ẵ'],
            'ẵ': ['ă', 'ắ', 'ằ', 'ặ', 'ẳ'],
            'ặ': ['ă', 'ắ', 'ằ', 'ẳ', 'ẵ'],
            'ẹ': ['e', 'é', 'è', 'ẻ', 'ẽ'],
            'ẻ': ['e', 'é', 'è', 'ẽ', 'ẹ'],
            'ẽ': ['e', 'é', 'è', 'ẻ', 'ẹ'],
            'ế': ['ê', 'ề', 'ể', 'ễ', 'ệ'],
            'ề': ['ê', 'ế', 'ể', 'ễ', 'ệ'],
            'ể': ['ê', 'ế', 'ề', 'ễ', 'ệ'],
            'ễ': ['ê', 'ế', 'ề', 'ể', 'ệ'],
            'ệ': ['ê', 'ế', 'ề', 'ể', 'ễ'],
            'ỉ': ['i', 'í', 'ì', 'ĩ', 'ị'],
            'ị': ['i', 'í', 'ì', 'ỉ', 'ĩ'],
            'ọ': ['o', 'ó', 'ò', 'ỏ', 'õ'],
            'ỏ': ['o', 'ó', 'ò', 'õ', 'ọ'],
            'ố': ['ô', 'ồ', 'ổ', 'ỗ', 'ộ'],
            'ồ': ['ô', 'ố', 'ổ', 'ỗ', 'ộ'],
            'ổ': ['ô', 'ố', 'ồ', 'ỗ', 'ộ'],
            'ỗ': ['ô', 'ố', 'ồ', 'ổ', 'ộ'],
            'ộ': ['ô', 'ố', 'ồ', 'ổ', 'ỗ'],
            'ớ': ['ơ', 'ờ', 'ở', 'ỡ', 'ợ'],
            'ờ': ['ơ', 'ớ', 'ở', 'ỡ', 'ợ'],
            'ở': ['ơ', 'ớ', 'ờ', 'ỡ', 'ợ'],
            'ỡ': ['ơ', 'ớ', 'ờ', 'ở', 'ợ'],
            'ợ': ['ơ', 'ớ', 'ờ', 'ở', 'ỡ'],
            'ụ': ['u', 'ú', 'ù', 'ủ', 'ũ'],
            'ủ': ['u', 'ú', 'ù', 'ũ', 'ụ'],
            'ứ': ['ư', 'ừ', 'ử', 'ữ', 'ự'],
            'ừ': ['ư', 'ứ', 'ử', 'ữ', 'ự'],
            'ử': ['ư', 'ứ', 'ừ', 'ữ', 'ự'],
            'ữ': ['ư', 'ứ', 'ừ', 'ử', 'ự'],
            'ự': ['ư', 'ứ', 'ừ', 'ử', 'ữ'],
            'ỳ': ['y', 'ý', 'ỷ', 'ỹ', 'ỵ'],
            'ỵ': ['y', 'ý', 'ỳ', 'ỷ', 'ỹ'],
            'ỷ': ['y', 'ý', 'ỳ', 'ỹ', 'ỵ'],
            'ỹ': ['y', 'ý', 'ỳ', 'ỷ', 'ỵ']
        }
        self.eligibleCharacters = self.model.keys()
